package vn.start.focus.ui

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import vn.start.domain.model.ScheduleModel
import vn.start.domain.usecase.schedule.AddScheduleUseCase
import vn.start.domain.usecase.schedule.GetSchedulesForTaskUseCase
import javax.inject.Inject

/**
 * ViewModel for the Focus feature.
 * Handles focus/pomodoro timer related logic and schedule management.
 */
@HiltViewModel
class FocusViewModel @Inject constructor(
    private val addScheduleUseCase: AddScheduleUseCase,
    private val getSchedulesForTaskUseCase: GetSchedulesForTaskUseCase
) : ViewModel() {

    // UI State for loading and error handling
    private val _uiState = MutableStateFlow<FocusUiState>(FocusUiState.Idle)
    val uiState: StateFlow<FocusUiState> = _uiState.asStateFlow()

    /**
     * Insert a new schedule for a task.
     * @param taskId The ID of the task to schedule
     * @param startTime The start time as a Unix timestamp
     * @param duration The duration in seconds
     */
    fun insertSchedule(
        taskId: Int,
        startTime: Long,
        duration: Int
    ) {
        viewModelScope.launch {
            try {
                _uiState.value = FocusUiState.Loading
                val schedule = ScheduleModel(
                    id = 0, // ID will be generated by the database
                    taskId = taskId,
                    startTime = startTime,
                    endTime = startTime + duration
                )
                addScheduleUseCase(schedule)
                _uiState.value = FocusUiState.Success
            } catch (e: Exception) {
                _uiState.value = FocusUiState.Error(e.message ?: "Unknown error occurred")
            }
        }
    }

    /**
     * Get all schedules for a specific task.
     * @param taskId The ID of the task
     * @return Flow of schedules for the task
     */
    fun getSchedulesForTask(taskId: Int) = getSchedulesForTaskUseCase(taskId)

    /**
     * Reset the UI state to idle.
     */
    fun resetUiState() {
        _uiState.value = FocusUiState.Idle
    }
}

/**
 * Sealed class representing the UI state for the Focus feature.
 */
sealed class FocusUiState {
    data object Idle : FocusUiState()
    data object Loading : FocusUiState()
    data object Success : FocusUiState()
    data class Error(val message: String) : FocusUiState()
}