package vn.start.dashboard.ui

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import vn.start.domain.model.ScheduleModel
import vn.start.domain.usecase.schedule.AddScheduleUseCase
import vn.start.domain.usecase.task.GetAllTasksUseCase
import javax.inject.Inject

/**
 * ViewModel for the Dashboard feature.
 * Handles dashboard data display and task/schedule management.
 */
@HiltViewModel
class DashBoardViewModel @Inject constructor(
    private val addScheduleUseCase: AddScheduleUseCase,
    private val getAllTasksUseCase: GetAllTasksUseCase
) : ViewModel() {

    // UI State for loading and error handling
    private val _uiState = MutableStateFlow<DashboardUiState>(DashboardUiState.Idle)
    val uiState: StateFlow<DashboardUiState> = _uiState.asStateFlow()

    /**
     * Insert a new schedule for a task.
     * @param taskId The ID of the task to schedule
     * @param startTime The start time as a Unix timestamp
     * @param duration The duration in seconds
     */
    fun insertSchedule(
        taskId: Int,
        startTime: Long,
        duration: Int
    ) {
        viewModelScope.launch {
            try {
                _uiState.value = DashboardUiState.Loading
                val schedule = ScheduleModel(
                    id = 0, // ID will be generated by the database
                    taskId = taskId,
                    startTime = startTime,
                    endTime = startTime + duration
                )
                addScheduleUseCase(schedule)
                _uiState.value = DashboardUiState.Success
            } catch (e: Exception) {
                _uiState.value = DashboardUiState.Error(e.message ?: "Unknown error occurred")
            }
        }
    }

    /**
     * Get all tasks for the dashboard.
     * @return Flow of tasks
     */
    fun getAllTasks() = getAllTasksUseCase()

    /**
     * Reset the UI state to idle.
     */
    fun resetUiState() {
        _uiState.value = DashboardUiState.Idle
    }
}

/**
 * Sealed class representing the UI state for the Dashboard feature.
 */
sealed class DashboardUiState {
    data object Idle : DashboardUiState()
    data object Loading : DashboardUiState()
    data object Success : DashboardUiState()
    data class Error(val message: String) : DashboardUiState()
}