package vn.start.planning.ui

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import vn.start.domain.model.TaskModel
import vn.start.domain.model.TaskStatusModel
import vn.start.domain.usecase.task.AddTaskUseCase
import vn.start.domain.usecase.task.DeleteTaskUseCase
import vn.start.domain.usecase.task.GetAllTasksUseCase
import vn.start.domain.usecase.task.UpdateTaskUseCase
import javax.inject.Inject

/**
 * ViewModel for the Planning feature.
 * Handles task planning and management operations.
 */
@HiltViewModel
class PlanningViewModel @Inject constructor(
    private val getAllTasksUseCase: GetAllTasksUseCase,
    private val addTaskUseCase: AddTaskUseCase,
    private val updateTaskUseCase: UpdateTaskUseCase,
    private val deleteTaskUseCase: DeleteTaskUseCase
) : ViewModel() {

    // UI State for loading and error handling
    private val _uiState = MutableStateFlow<PlanningUiState>(PlanningUiState.Idle)
    val uiState: StateFlow<PlanningUiState> = _uiState.asStateFlow()

    /**
     * Get all tasks for planning.
     * @return Flow of tasks
     */
    fun getAllTasks() = getAllTasksUseCase()

    /**
     * Add a new task.
     * @param title The task title
     * @param description The task description
     * @param priority The task priority (0=low, 1=medium, 2=high)
     */
    fun addTask(
        title: String,
        description: String = "",
        priority: Int = 1
    ) {
        viewModelScope.launch {
            try {
                _uiState.value = PlanningUiState.Loading
                val now = System.currentTimeMillis()
                val task = TaskModel(
                    id = 0, // ID will be generated by the database
                    title = title,
                    description = description,
                    priority = priority,
                    status = TaskStatusModel.PENDING,
                    createdAt = now,
                    updatedAt = now
                )
                addTaskUseCase(task)
                _uiState.value = PlanningUiState.Success
            } catch (e: Exception) {
                _uiState.value = PlanningUiState.Error(e.message ?: "Unknown error occurred")
            }
        }
    }

    /**
     * Update an existing task.
     * @param task The task to update
     */
    fun updateTask(task: TaskModel) {
        viewModelScope.launch {
            try {
                _uiState.value = PlanningUiState.Loading
                updateTaskUseCase(task)
                _uiState.value = PlanningUiState.Success
            } catch (e: Exception) {
                _uiState.value = PlanningUiState.Error(e.message ?: "Unknown error occurred")
            }
        }
    }

    /**
     * Delete a task.
     * @param task The task to delete
     */
    fun deleteTask(task: TaskModel) {
        viewModelScope.launch {
            try {
                _uiState.value = PlanningUiState.Loading
                deleteTaskUseCase(task)
                _uiState.value = PlanningUiState.Success
            } catch (e: Exception) {
                _uiState.value = PlanningUiState.Error(e.message ?: "Unknown error occurred")
            }
        }
    }

    /**
     * Reset the UI state to idle.
     */
    fun resetUiState() {
        _uiState.value = PlanningUiState.Idle
    }
}

/**
 * Sealed class representing the UI state for the Planning feature.
 */
sealed class PlanningUiState {
    data object Idle : PlanningUiState()
    data object Loading : PlanningUiState()
    data object Success : PlanningUiState()
    data class Error(val message: String) : PlanningUiState()
}
